### ISSUE TITLE
Not working in Codeigniter

### ISSUE THREAD

**Issue by gymikechen** [Fahl-Design/log4php-slack-appender#2]
as title

**Comment by Fahl-Design** [comment]
Hi,
Could you please provide some more details, like an error log or message

I will take a look at it asap

regards

**Comment by gymikechen** [comment]
I installed this in codeigniter 2 via composer with fukata/ci-log4php.
Installed project folder was under vendor, instead of third-party.
There's no error message, log output was in file not slack notification.

**Comment by Fahl-Design** [comment]
ok so "fukata/ci-log4php" is running as expected? (If not follow installation instructions)
did you set up the appender config for the slack appender in "log4php.properties" file?

**Comment by Fahl-Design** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Codeignitor Testing](https://trello.com/c/gapwBjkV/7-codeignitor-testing)
